import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Slider from "../../components/Slider";
import { motion } from "framer-motion";
import "vanilla-tilt";
import ImageGallery from "../../components/ImageGallery";

const Index = () => {
  const [isVisible, setIsVisible] = useState(true);

  function AnimationEnds() {
    setIsVisible(true);
  }

  return (
    <div>
      <Head>
        <title>Artists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-x-hidden">
        {/* <Slider trigger={AnimationEnds} /> */}

        {isVisible ? (
          <>

            {/* El de abajo llegveria de llevar padding instead */}
            <motion.div className="min-h-screen bg-black flex flex-col items-center justify-center text-white font-body">
              <div className="grid grid-cols-2 min-h-screen justify-center items-center p-20">
                {/* Images galley */}
                <ImageGallery />
                {/* Title and text */}
                <div className="flex flex-col justify-center items-center">
                  <h1 className="uppercase text-center text-9xl py-16 font-bold">
                    <div>Artes</div>
                    <div className="relative transform -translate-y-8">
                      Visuales
                    </div>
                  </h1>
                  <div className="ma max-w-lg relative transform -translate-y-16 text-center">
                    <p>
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Possimus minus assumenda non nesciunt enim? Praesentium
                      ipsum fuga harum quaerat possimus!
                    </p>
                  </div>
                </div>
                <div className="flex flex-col justify-center items-center">
                  <h1 className="uppercase text-center text-9xl py-16 font-bold">
                    <div>Artes</div>
                    <div className="relative transform -translate-y-8">
                      Visuales
                    </div>
                  </h1>
                  <div className="ma max-w-lg relative transform -translate-y-16 text-center">
                    <p>
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Possimus minus assumenda non nesciunt enim? Praesentium
                      ipsum fuga harum quaerat possimus!
                    </p>
                  </div>
                </div>
                <ImageGallery />
                {/* Title and text */}

                <ImageGallery />
                {/* Title and text */}
                <div className="flex flex-col justify-center items-center">
                  <h1 className="uppercase text-center text-9xl py-16 font-bold">
                    <div>Artes</div>
                    <div className="relative transform -translate-y-8">
                      Visuales
                    </div>
                  </h1>
                  <div className="ma max-w-lg relative transform -translate-y-16 text-center">
                    <p>
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Possimus minus assumenda non nesciunt enim? Praesentium
                      ipsum fuga harum quaerat possimus!
                    </p>
                  </div>
                </div>
              </div>
            </motion.div>
          </>
        ) : (
          <>
            <div className="min-h-screen bg-black"></div>
          </>
        )}
      </div>
    </div>
  );
};

export default Index;
