import React, { useState, useEffect } from "react";
import Nav from "../../components/Nav";
import Head from "next/head";
import Image from "next/image";
import Slider from "../../components/Slider";
import { motion } from "framer-motion";
import ImageGallery from "../../components/ImageGallery";
import Swiper from "../../components/Swiper";
import { sanityClient } from "../../sanity";

const Index = ({
  artistsInfo,
  aMusicalesImgs,
  aMixtasImgs,
  aVisualesImgs,
  aMixtasCover,
  aMusicalesCover,
  aVisualesCover,
}) => {
  const [isVisible, setIsVisible] = useState(true);

  // TODO: SPREAD OPPERATE ALL THE aArtImgs while adding new IMG from the artist info

  function AnimationEnds() {
    setIsVisible(true);
  }

  const { aMixtas, aMusicales, aVisuales} = artistsInfo[0];

  // const defactor = aMusicalesCover.filter((img)=>img.mainImage)

  const aMusicalesImgsSlide = [aMusicalesCover, ...aMusicalesImgs];
  const aMixtasImgsSlide = [ aMixtasCover, ...aMixtasImgs ];
  const aVisualesImgsSlide = [aVisualesCover, ...aVisualesImgs];
  
  console.log('====================================');
  console.log(aMusicalesImgsSlide);
  console.log('====================================');


  return (
    <div>
      <Head>
        <title>Artists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-x-hidden">
        {/* <Slider trigger={AnimationEnds} /> */}

        {isVisible ? (
          <>
            {/* TODO: REMEMBER RESPONSIVE SWIPPERS */}
            <Nav />
            {/* El de abajo llegveria de llevar padding instead */}
            <motion.div className="min-h-screen bg-black flex flex-col items-center justify-center text-white font-body">
              <div className="grid lg:grid-cols-2 min-h-screen justify-center items-center py-20 sm:p-10 lg:p-20">
                {/* Images galley */}
                {/* <div className="hidden">
                  <ImageGallery />
                </div> */}
                {/* Title and text */}
                <div className="hidden lg:block">
                  <Swiper list={aMusicalesImgsSlide} />
                </div>
                {/* <div className="hidden">
                  <ImageGallery />
                </div> */}
                {/* Title and text */}
                <div className="flex flex-col justify-center items-center">
                  <h1 className="uppercase text-center text-5xl sm:text-7xl  2xl:text-9xl py-4 lg:py-16 font-bold">
                    <div>Artes</div>
                    <div className="relative transform -translate-y-2 lg:-translate-y-4 2xl:-translate-y-8">
                      Musicales
                    </div>
                  </h1>
                  <div className="max-w-lg relative transform -translate-y-4 lg:-translate-y-8 2xl:-translate-y-16 text-center py-8 lg:py-0 text-xs md:text-lg">
                    <p>{aMusicales}</p>
                  </div>
                </div>
                <div className="block lg:hidden pb-16">
                  <Swiper list={aMusicalesImgsSlide} />
                </div>

                <div className="flex flex-col justify-center items-center">
                  <h1 className="uppercase text-center text-5xl sm:text-7xl  2xl:text-9xl  py-4 lg:py-16 font-bold">
                    <div>Artes</div>
                    <div className="relative transform -translate-y-2 lg:-translate-y-4 2xl:-translate-y-8">
                      Visuales
                    </div>
                  </h1>
                  <div className="max-w-lg relative transform -translate-y-4 lg:-translate-y-8 2xl:-translate-y-16 text-center py-8 lg:py-0 text-xs md:text-lg">
                    <p>{aVisuales}</p>
                  </div>
                </div>
                {/* <div className="hidden">
                  <ImageGallery />
                </div> */}
                <div className="pb-16 lg:pb-0">
                  <Swiper list={aVisualesImgsSlide} />
                </div>
                <div className="hidden lg:block">
                  <Swiper list={aMixtasImgsSlide} />
                </div>
                {/* Title and text */}
                <div className="flex flex-col justify-center items-center">
                  <h1 className="uppercase text-center text-5xl sm:text-7xl  2xl:text-9xl py-4 lg:py-16 font-bold">
                    <div>Artes</div>
                    <div className="relative transform -translate-y-2 lg:-translate-y-4 2xl:-translate-y-8">
                      Mixtas
                    </div>
                  </h1>
                  <div className="max-w-lg relative transform -translate-y-4 lg:-translate-y-8 2xl:-translate-y-16 text-center py-8 lg:py-0 text-xs md:text-lg">
                    <p>{aMixtas}</p>
                  </div>
                </div>
                <div className="block lg:hidden pb-16">
                  <Swiper list={aMixtasImgsSlide} />
                </div>
              </div>
            </motion.div>
          </>
        ) : (
          <>
            <div className="min-h-screen bg-black"></div>
          </>
        )}
      </div>
    </div>
  );
};

export const getStaticProps = async ({ params }) => {
// export const getServerSideProps = async ({ params }) => {
  const query = `*[_type == "artists"]{
    aVisuales,
    aMusicales,
    aMixtas,
    aVisImgs{
                    asset->{
                        _id,
                        url
                    }
                },
    aMusImgs{
                    asset->{
                        _id,
                        url
                    }
                },
    aMixImgs{
                    asset->{
                        _id,
                        url
                    }
                }
  
  }`;
  const aMusicalesQuery = `*[_type == "posts" && category == "artesMusicales" && cover != "Cover"]{
    slug,
    mainImage{
                    asset->{
                        _id,
                        url
                    }
                }
}`;
  const aMixtasQuery = `*[_type == "posts" && category == "artesMixtas" && cover != "Cover"]{
    slug,
    mainImage{
                    asset->{
                        _id,
                        url
                    }
                }
}`;
  const aVisualesQuery = `*[_type == "posts" && category == "artesVisuales" && cover != "Cover"]{
    slug,
    mainImage{
                    asset->{
                        _id,
                        url
                    }
                }
}`;
  const aVisualesQueryCover = `*[_type == "posts" && category == "artesVisuales" && cover == "Cover"][0]{
    mainImage{
                    asset->{
                        _id,
                        url
                    }
                }
}`;
  const aMixtasQueryCover = `*[_type == "posts" && category == "artesMixtas" && cover == "Cover"][0]{
    mainImage{
                    asset->{
                        _id,
                        url
                    }
                }
}`;
  const aMusicalesQueryCover = `*[_type == "posts" && category == "artesMusicales" && cover == "Cover"][0]{
    mainImage{
                    asset->{
                        _id,
                        url
                    }
                }
}`;

  const artistsInfo = await sanityClient.fetch(query);
  const aMusicalesImgs = await sanityClient.fetch(aMusicalesQuery);
  const aMixtasImgs = await sanityClient.fetch(aMixtasQuery);
  const aVisualesImgs = await sanityClient.fetch(aVisualesQuery);
  const aMixtasCover = await sanityClient.fetch(aMixtasQueryCover);
  const aMusicalesCover = await sanityClient.fetch(aMusicalesQueryCover);
  const aVisualesCover = await sanityClient.fetch(aVisualesQueryCover);

  return {
    props: {
      artistsInfo,
      aMusicalesImgs,
      aMixtasImgs,
      aVisualesImgs,
      aMixtasCover,
      aMusicalesCover,
      aVisualesCover
    },
  };
};

export default Index;
