import React from 'react'
import Head from "next/head";

// Component accepts a props object with the following properties:
// - title: the title of the page to be shown in the browser tab
export default function SEOComponent({title}) {
    return (
      <Head>
            <title>{ title }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    );
}
