import React, { useState, useEffect } from "react";
import Nav from "../components/Nav";
import Head from "next/head";
import Image from "next/image";
import Slider from "../components/Slider";
import { sanityClient } from "../sanity";
import { motion, AnimateSharedLayout, AnimatePresence } from "framer-motion";
import Members from "../components/Members"

const getToKnowUs = ({ members, page }) => {


  const { description, mainImage } = page;

  return (
    <div>
      <Head>
        <title>Meet Out Crew</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-x-hidden">
        <s className="block">
          <Nav />
          {/* md:hidden block  */}
          <div className="absolute min-h-screen min-w-full bg-black">
            {mainImage ? (
              <Image
                className="h-full w-full object-cover opacity-80"
                src={mainImage.asset.url}
                alt=""
                layout="fill"
                priority={true}
              />
            ) : (
              <Image
                className="h-full w-full object-cover opacity-50"
                src="/BWBG.jpg"
                alt=""
                layout="fill"
                priority={true}
              />
            )}
          </div>
          {/* <div className="md:block hidden absolute min-h-screen min-w-full bg-black">
            <Image
              className="h-full w-full object-cover opacity-80"
              src="/BWBG.jpg"
              alt=""
              layout="fill"
              priority={true}
            />
          </div> */}
          {/* remember the padding 20 */}
        </s>
        <div className="max-h-screen bg-black  items-center justify-center text-white font-body">
          {/* Head Title */}
          <div className="relative flex flex-col pt-20 md:pt-24 xl:pt-4">
            <div className="block lg:hidden">
              <h1 className="relative text-7xl uppercase text-center md:text-9xl pt-8 pb-0  font-bold ">
                Meet our
              </h1>
              <h1 className="relative text-7xl uppercase text-center md:text-9xl pb-8  font-bold ">
                team.
              </h1>
            </div>
            <div className="hidden lg:block">
              <h1 className="relative text-7xl uppercase text-center md:text-9xl pt-16 pb-8  font-bold ">
                Meet our team.
              </h1>
            </div>
          </div>
          {/* Team description */}
          {/* <div className="px-10">
            <div className="relative flex justify-center items-center text-center pb-10 md:text-xl text-md uppercase font-bold ">
              <div className="max-w-5xl">
                <h3>
                  {description
                    ? description
                    : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut nobis nemo recusandae distinctio hic rerum enim assumenda animi. Voluptatum consectetur assumenda quia facilis eos inventore iure, eligendi illum modi soluta!"}
                </h3>
              </div>
            </div>
          </div> */}
          {/* Members */}
          <div className="relative flex flex-col justify-center items-center md:flex-row">
            <AnimateSharedLayout>
              <motion.div
                layout
                // initial={{ borderRadius: 25 }}
              >
                {" "}
                {members &&
                  members.map((member, index) => (
                    <Members member={member} key={index} />
                  ))}
              </motion.div>
            </AnimateSharedLayout>
            {/* Individual card */}
            {/* Second */}
          </div>
        </div>
      </div>
    </div>
  );
};

export const getStaticProps = async ({ params }) => {
  // export const getServerSideProps = async ({ params }) => {
  const membersQuery = `*[_type == "members"]| order(order){
    name,
    position,
    biography,
    mainImage{
                    asset->{
                        _id,
                        url
                    }
                },
  }`;
  const pageQuery = `*[_type == "team"][0]{
 
    mainImage{
                    asset->{
                        _id,
                        url
                    }
                },
  }`;

  //    description,

  const members = await sanityClient.fetch(membersQuery);
  const page = await sanityClient.fetch(pageQuery);

  return {
    props: {
      members,
      page,
    },
  };
};

export default getToKnowUs;
