import React from 'react'
import Nav from "../components/Nav";
import Head from "next/head";

const getToKnowUs = () => {
    return (
      <div>
        <Head>
          <title>Meet Out Team</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Nav />
                <div className="min-h-screen bg-black grid  md:grid-cols-2 items-center justify-center text-white font-body">

                </div>
            </div>
      </div>
    );
}

export default getToKnowUs
